language:
  - cpp

dist: xenial

sudo: false

compiler:
  - gcc

branches:
  only:
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-6

env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - readonly PARENT_DIR=$(pwd)
  - eval "${MATRIX_EVAL}"

  # build from source latest eigen
  - git clone https://github.com/eigenteam/eigen-git-mirror.git
  - cd eigen-git-mirror
  - mkdir build && cd build && cmake ../ && make && sudo make install

before_script:
  - pyenv versions
  - pyenv global 3.6.7
  - ls -al $(python-config --prefix)/bin $(python-config --prefix)/lib $(python-config --prefix)/include

script:
  - cd ${PARENT_DIR}
  - mkdir build
  - cd build
  - |
    cmake \
      -DBUILD_EXAMPLES=ON \
      -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.6 \
      -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.6m.so \
      -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.6m \
      ..
  - cmake --build .
  - make test

notifications:
  email: false
